# Generated by Django 4.0.6 on 2022-07-20 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rims'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rims',
            name='date',
            field=models.DateField(verbose_name='drinking time'),
        ),
        migrations.AlterField(
            model_name='rims',
            name='rim',
            field=models.CharField(choices=[('S', 'Salt'), ('SG', 'Sugar'), ('NO', 'No Rim')], default='S', max_length=2),
        ),
    ]
