# Generated by Django 4.0.6 on 2022-07-20 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_mix'),
    ]

    operations = [
        migrations.AddField(
            model_name='tequila',
            name='mixes',
            field=models.ManyToManyField(to='main_app.mix'),
        ),
    ]
